<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Installing-and-verifying-PyTorch" data-toc-modified-id="Installing-and-verifying-PyTorch-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Installing and verifying PyTorch</a></span><ul class="toc-item"><li><span><a href="#Install-PyTorch" data-toc-modified-id="Install-PyTorch-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Install PyTorch</a></span></li><li><span><a href="#Import-libraries" data-toc-modified-id="Import-libraries-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Import libraries</a></span></li><li><span><a href="#Verify-PyTorch-install" data-toc-modified-id="Verify-PyTorch-install-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Verify PyTorch install</a></span></li></ul></li><li><span><a href="#Tensors" data-toc-modified-id="Tensors-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Tensors</a></span><ul class="toc-item"><li><span><a href="#Creating-a-Tensor" data-toc-modified-id="Creating-a-Tensor-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Creating a Tensor</a></span></li><li><span><a href="#Tensors-on-GPGPU" data-toc-modified-id="Tensors-on-GPGPU-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Tensors on GPGPU</a></span></li><li><span><a href="#Operations-with-Tensors" data-toc-modified-id="Operations-with-Tensors-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>Operations with Tensors</a></span></li></ul></li></ul></div>

## Installing and verifying PyTorch

In [1]:
import sys
print('Python version:{}'.format(sys.version[:23]))

Python version:3.6.6 |Anaconda, Inc.| 


### Install PyTorch

In [2]:
# Modify the path to check CUDA version on your system
with open('/usr/local/cuda/version.txt') as f:
    print(f.read()) 

CUDA Version 9.2.148



In [3]:
!conda install --yes --prefix {sys.prefix} pytorch torchvision cuda92 -c pytorch
# or !{sys.executable} -m pip install pytorch torchvision cuda92

Solving environment: done

# All requested packages already installed.



### Import libraries

In [4]:

import torch
print('Torch version:{}'.format(torch.__version__))

Torch version:0.4.1


### Verify PyTorch install

In [5]:
cpu_tensor = torch.rand(3,5)
print('Tensor on CPU:',cpu_tensor)
if torch.cuda.is_available():
    gpu_tensor = cpu_tensor.cuda()
    print('Tensor on GPGPU:',gpu_tensor)
else:
    print('Torch on CUDA not available')

Tensor on CPU: tensor([[0.8154, 0.1116, 0.9855, 0.6716, 0.8427],
        [0.1701, 0.6120, 0.4625, 0.3445, 0.3623],
        [0.1144, 0.0266, 0.3921, 0.4525, 0.8265]])
Tensor on GPGPU: tensor([[0.8154, 0.1116, 0.9855, 0.6716, 0.8427],
        [0.1701, 0.6120, 0.4625, 0.3445, 0.3623],
        [0.1144, 0.0266, 0.3921, 0.4525, 0.8265]], device='cuda:0')


## Tensors

### Creating a Tensor

In [6]:
python_list = [1, 2, 3, 4]
print(python_list)
tensor_from_list = torch.tensor(python_list)
print(tensor_from_list)

[1, 2, 3, 4]
tensor([1, 2, 3, 4])


In [7]:
import numpy as np
numpy_array = np.array([5,6,7,8])
print(numpy_array)
tensor_from_numpy_array = torch.from_numpy(numpy_array)
print(tensor_from_numpy_array)

[5 6 7 8]
tensor([5, 6, 7, 8])


In [8]:
numpy_array_from_tensor = tensor_from_numpy_array.numpy()
print(type(numpy_array_from_tensor),numpy_array_from_tensor)

<class 'numpy.ndarray'> [5 6 7 8]


In [9]:
all_ones = torch.ones(3,4)
print(all_ones)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [10]:
all_zeros = torch.zeros(3,4)
print(all_zeros)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [11]:
all_random = torch.rand(3,4)
print(all_random)

tensor([[0.8669, 0.5278, 0.7756, 0.0596],
        [0.2067, 0.7052, 0.0145, 0.0369],
        [0.7459, 0.5661, 0.1640, 0.1375]])


In [12]:
all_float = torch.FloatTensor(3,4)
print(all_float)

tensor([[-1.3369e-16,  3.0816e-41,  1.6816e-44,  0.0000e+00],
        [        nan,  0.0000e+00,  6.4076e+07,  2.0706e-19],
        [ 7.3909e+22,  3.0492e-41,  2.6279e+30,  4.5656e-41]])


In [13]:
# slice and dice examples
print(all_random[1,:])

tensor([0.2067, 0.7052, 0.0145, 0.0369])


In [14]:
print(all_random[:,2])

tensor([0.7756, 0.0145, 0.1640])


In [15]:
print(all_random[0:2,0:2])

tensor([[0.8669, 0.5278],
        [0.2067, 0.7052]])


### Tensors on GPGPU

In [16]:
gpgpu_tensor = all_random.cuda()
print(gpgpu_tensor)

tensor([[0.8669, 0.5278, 0.7756, 0.0596],
        [0.2067, 0.7052, 0.0145, 0.0369],
        [0.7459, 0.5661, 0.1640, 0.1375]], device='cuda:0')


In [17]:
cpu_tensor = gpgpu_tensor.cpu()
print(cpu_tensor)

tensor([[0.8669, 0.5278, 0.7756, 0.0596],
        [0.2067, 0.7052, 0.0145, 0.0369],
        [0.7459, 0.5661, 0.1640, 0.1375]])


In [18]:
print(gpgpu_tensor+cpu_tensor)

RuntimeError: Expected object of type torch.cuda.FloatTensor but found type torch.FloatTensor for argument #3 'other'

In [19]:
cpu_tensor = cpu_tensor * 2
gpgpu_tensor = cpu_tensor.to('cuda:0')
print(gpgpu_tensor)

tensor([[1.7338, 1.0556, 1.5512, 0.1193],
        [0.4135, 1.4105, 0.0290, 0.0738],
        [1.4919, 1.1323, 0.3281, 0.2749]], device='cuda:0')


In [20]:
print(cpu_tensor.device)
print(gpu_tensor.device)

cpu
cuda:0


In [21]:
gpgpu_tensor = torch.rand((3,4),device=torch.device('cuda'))
print(gpgpu_tensor)

tensor([[0.4679, 0.1410, 0.1218, 0.8473],
        [0.0770, 0.1401, 0.6140, 0.4993],
        [0.8017, 0.0937, 0.8986, 0.4896]], device='cuda:0')


### Operations with Tensors

In [22]:
x = torch.rand(3,4)
y = torch.rand(3,4)
print(x,y)

tensor([[0.2508, 0.9035, 0.6209, 0.9725],
        [0.7348, 0.2872, 0.7109, 0.9939],
        [0.6496, 0.5582, 0.5093, 0.4237]]) tensor([[0.9911, 0.6459, 0.1771, 0.6210],
        [0.3322, 0.3387, 0.8688, 0.8867],
        [0.3151, 0.1992, 0.1532, 0.9190]])


In [23]:
print(torch.mul(x,y))

tensor([[0.2485, 0.5836, 0.1100, 0.6040],
        [0.2441, 0.0973, 0.6176, 0.8813],
        [0.2047, 0.1112, 0.0780, 0.3894]])


In [24]:
print(x*y)

tensor([[0.2485, 0.5836, 0.1100, 0.6040],
        [0.2441, 0.0973, 0.6176, 0.8813],
        [0.2047, 0.1112, 0.0780, 0.3894]])


In [25]:
print(x)
x.mul_(y)
print(x)

tensor([[0.2508, 0.9035, 0.6209, 0.9725],
        [0.7348, 0.2872, 0.7109, 0.9939],
        [0.6496, 0.5582, 0.5093, 0.4237]])
tensor([[0.2485, 0.5836, 0.1100, 0.6040],
        [0.2441, 0.0973, 0.6176, 0.8813],
        [0.2047, 0.1112, 0.0780, 0.3894]])


# Variables

In [26]:
print(x.data)

tensor([[0.2485, 0.5836, 0.1100, 0.6040],
        [0.2441, 0.0973, 0.6176, 0.8813],
        [0.2047, 0.1112, 0.0780, 0.3894]])


In [27]:
print(x.grad)

None


In [28]:
print(x.grad_fn)

None


In [29]:
x.requires_grad_(True)

tensor([[0.2485, 0.5836, 0.1100, 0.6040],
        [0.2441, 0.0973, 0.6176, 0.8813],
        [0.2047, 0.1112, 0.0780, 0.3894]], requires_grad=True)

In [30]:
z = x+y
print(z.requires_grad)

True


In [31]:
print(z.grad_fn)

# Machine Learning - Logistic Regression

In [32]:
# load dslib
DSLIB_HOME = '../datasetslib'
import sys
if not DSLIB_HOME in sys.path:
    sys.path.append(DSLIB_HOME)
%reload_ext autoreload
%autoreload 2
import datasetslib as dslib

# set the datasets root folder before you do the datasetslib import
import os
dslib.dsroot = os.path.join(os.path.expanduser('~'),'datasets')

from datasetslib.utils import imutil
from datasetslib.utils import nputil
from datasetslib.mnist import MNIST

In [46]:
mnist=MNIST()

# prepare x and y data
mnist.y_onehot = True
mnist.x_layout = imutil.LAYOUT_NP

x_train,y_train,x_test,y_test=mnist.load_data()

x_train = mnist.load_images(x_train)
y_train = nputil.onehot(y_train)
x_test = mnist.load_images(x_test)
y_test = nputil.onehot(y_test)

print('Loaded x and y')
print('Train: x:{}, y:{}'.format(x_train.shape,y_train.shape))
print('Test: x:{}, y:{}'.format(x_test.shape,y_test.shape))

Already exists: /home/armando/datasets/mnist/train-images-idx3-ubyte.gz
Already exists: /home/armando/datasets/mnist/train-labels-idx1-ubyte.gz
Already exists: /home/armando/datasets/mnist/t10k-images-idx3-ubyte.gz
Already exists: /home/armando/datasets/mnist/t10k-labels-idx1-ubyte.gz
Extracting and rearchiving as jpg files...
/home/armando/datasets/mnist/train-images-idx3-ubyte.gz
Reading from  /home/armando/datasets/mnist/train-images-idx3-ubyte.gz
Reading from  /home/armando/datasets/mnist/train-labels-idx1-ubyte.gz
Saving  train
Zip file not modified
/home/armando/datasets/mnist/train-images-idx3-ubyte.gz
Reading from  /home/armando/datasets/mnist/t10k-images-idx3-ubyte.gz
Reading from  /home/armando/datasets/mnist/t10k-labels-idx1-ubyte.gz
Saving  test
Zip file not modified
Loading in x and y... start
Loading in x and y... done
Loaded x and y
Train: x:(60000, 784), y:(60000, 10)
Test: x:(10000, 784), y:(10000, 10)


In [ ]:
# define hyperparameters
learning_rate = 0.0000001
n_epochs = 50
epsilon = 1e-6

# define input images
x = torch.tensor(x_train,dtype=torch.float32,requires_grad=False)
# define output labels
y = torch.tensor(y_train,dtype=torch.float32,requires_grad=False)

# model parameters
w = torch.tensor(torch.zeros([mnist.n_features, mnist.n_classes]), 
                 requires_grad=True)
b = torch.tensor(torch.zeros([mnist.n_classes]),
                 requires_grad=True)



In [78]:
# train and test

for epoch in range(n_epochs):
    # Forward prop
    logits = torch.add(torch.matmul(x, w), b)
    softmax = torch.nn.Softmax(dim=1)
    y_hat = softmax(logits)
    
    # Calculate loss
    y_hat_clipped = torch.clamp(y_hat, epsilon, 1 - epsilon)
    y_hat_log = torch.log(y_hat_clipped)
    cross_entropy = -torch.sum(y * y_hat_log)
    loss = torch.mean(cross_entropy)
    
    # Back prop
    for param in [w,b]:
        if not param.grad is None: param.grad.data.zero_()
    loss.backward()
    w.data -= learning_rate * w.grad.data
    b.data -= learning_rate * b.grad.data
    
    # Calculate and print train set accuracy
    _,y_idx = torch.max(y,1)
    _,y_hat_idx = torch.max(y_hat,1)
    
    predictions_check = torch.eq(y_hat_idx, y_idx)
    accuracy_score = torch.mean(torch.tensor(predictions_check, 
                                             dtype=torch.float32))
    print('epoch {0:04d}  accuracy={1:.8f}'
          .format(epoch, accuracy_score))

epoch 0000  accuracy=0.09871667
epoch 0001  accuracy=0.66996664
epoch 0002  accuracy=0.72711664
epoch 0003  accuracy=0.74848336
epoch 0004  accuracy=0.76136667
epoch 0005  accuracy=0.76830000
epoch 0006  accuracy=0.77578336
epoch 0007  accuracy=0.78111666
epoch 0008  accuracy=0.78503335
epoch 0009  accuracy=0.78770000
epoch 0010  accuracy=0.78920001
epoch 0011  accuracy=0.78986669
epoch 0012  accuracy=0.78933334
epoch 0013  accuracy=0.79176664
epoch 0014  accuracy=0.79231668
epoch 0015  accuracy=0.79488331
epoch 0016  accuracy=0.79726666
epoch 0017  accuracy=0.79925001
epoch 0018  accuracy=0.80168331
epoch 0019  accuracy=0.80313331
epoch 0020  accuracy=0.80543333
epoch 0021  accuracy=0.80669999
epoch 0022  accuracy=0.80739999
epoch 0023  accuracy=0.80763334
epoch 0024  accuracy=0.80841666
epoch 0025  accuracy=0.81064999
epoch 0026  accuracy=0.81146669
epoch 0027  accuracy=0.81223333
epoch 0028  accuracy=0.81150001
epoch 0029  accuracy=0.81161666
epoch 0030  accuracy=0.81050003
epoch 00

# Deep Learning - Image Classification

In [127]:
learning_rate = 0.001
n_epochs = 50
model = torch.nn.Sequential(torch.nn.Linear(784,512),
                          torch.nn.ReLU(),
                          torch.nn.Linear(512,256),
                          torch.nn.ReLU(),
                          torch.nn.Linear(256,10))
loss_f = torch.nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(),lr=learning_rate)

for epoch in range(n_epochs):
    y_hat = model(x)
    _,y_idx = torch.max(y,1)
    loss = loss_f(y_hat,y_idx)
    
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    
    _,y_hat_idx = torch.max(y_hat,1)
    
    predictions_check = torch.eq(y_hat_idx, y_idx)
    accuracy_score = torch.mean(torch.tensor(predictions_check, dtype=torch.float32))
    print('epoch {0:04d}  accuracy={1:.8f}'
          .format(epoch, accuracy_score))

epoch 0000  accuracy=0.08321667
epoch 0001  accuracy=0.31131667
epoch 0002  accuracy=0.21960001
epoch 0003  accuracy=0.34123334
epoch 0004  accuracy=0.37403333
epoch 0005  accuracy=0.49971667
epoch 0006  accuracy=0.52168334
epoch 0007  accuracy=0.52668333
epoch 0008  accuracy=0.52846664
epoch 0009  accuracy=0.58356667
epoch 0010  accuracy=0.69476664
epoch 0011  accuracy=0.74675000
epoch 0012  accuracy=0.72381669
epoch 0013  accuracy=0.69466668
epoch 0014  accuracy=0.70195001
epoch 0015  accuracy=0.73746669
epoch 0016  accuracy=0.76611668
epoch 0017  accuracy=0.78046668
epoch 0018  accuracy=0.79783332
epoch 0019  accuracy=0.81875002
epoch 0020  accuracy=0.83628333
epoch 0021  accuracy=0.84516668
epoch 0022  accuracy=0.84745002
epoch 0023  accuracy=0.84791666
epoch 0024  accuracy=0.84890002
epoch 0025  accuracy=0.85294998
epoch 0026  accuracy=0.85921669
epoch 0027  accuracy=0.86693335
epoch 0028  accuracy=0.87440002
epoch 0029  accuracy=0.88108331
epoch 0030  accuracy=0.88630003
epoch 00